### ISSUE TITLE
[Android] [UI] As a user, I can see the loading animation while the app is fetching surveys

### ISSUE THREAD

**Issue by phongvhd93** [nimblehq/avishek-phong-kmm-ic#29]
# Why

To let the user know the application is fetching data and keep them occupied, we will show the loading animation on the Home screen when the app is fetching surveys.

# Acceptance Criteria 

- Show the animation with the following design

![Image](https://user-images.githubusercontent.com/22606906/230261285-b4d94b6f-9f9d-486e-a47c-71e9a7118c49.png)

[Figma](https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=34-178&t=1xiBQA7GNv0kEx7j-0)

**Comment by AVI5HEK** [comment]
@phongvhd93 This has been implemented as part of #37 How about we delete/archive this story?
